### PR TITLE
Avoid Finder permission dialog

### LINKED ISSUE #1: Possible refactor to use mdfind
Hi Sindre,

I've been using a small function to find installed apps in my Electron-based app, Browserosaurus. I thought I'd try replacing my function with your package but using AppleScript to "tell Finder" causes my app to display a Finder access permission dialog. Would you be up for a refactor of your package to avoid this? Here's what I'm using:

```ts
import { execFile } from 'child_process'
import { promisify } from 'util'

const execFileP = promisify(execFile)

async function appExists(nameOrBundleId: string): Promise<boolean> {
  const isBundleId = nameOrBundleId.includes('.')

  const query = isBundleId
    ? `kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == '${nameOrBundleId}'`
    : `kMDItemKind == 'Application' && kMDItemFSName == '${nameOrBundleId}.app'c`

  const { stdout: appPath } = await execFileP('mdfind', [query])

  return Boolean(appPath)
}
```

Let me know if you'd like a PR.

### PR DESCRIPTION
**Pull request by will-stone**
Uses mdfind to locate apps rather than AppleScript asking Finder.

Closes #1

### CODE REVIEW

**Comment by will-stone** [comment]
By the way, the "c" in the second query makes it case-insensitive. Please remove if that's more than you would like from this package.

**Comment by will-stone** [comment]
I don't know why the tests are failing; they pass locally. Maybe the Travis runner doesn't have mdfind? I've been using GitHub's Actions for Browserosaurus's tests: the `appExists` test passes: https://github.com/will-stone/browserosaurus/runs/857288105#step:9:12 🤷‍♂️

**Comment by sindresorhus** [comment]
Or maybe they disabled Spotlight.

**Comment by sindresorhus** [comment]
Doesn't matter. I'll just disable Travis for now. I'll eventually switch to GitHub Actions anyway.

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
